### PR TITLE
Update and rename README.md to README.txt

### LINKED ISSUE #14: Change the README to a .txt format
Also wrap the content sooner so the lines are not too long. Keep the bulleted format, but change the link syntax.

### PR DESCRIPTION
**Pull request by mbroz2**
Resolves #14

### CODE REVIEW

**Comment by steven1046** [comment]
We'll also need to update what file the generator generates here at the bottom: https://github.com/OpenLiberty/start.openliberty.io/blob/updateReadme/src/main/resources/templates/templates.json#L91

both lines

**Comment by mbroz2** [comment]
Updated!

**Review by steven1046 — APPROVED** [review]

**Comment by steven1046** [comment]
I'll need to generate a new server package for the deployment stage to use, or you could try the instructions in the README

**Comment by mbroz2** [comment]
I would like to leave that to you, but maybe wait until https://github.com/OpenLiberty/start.openliberty.io/pull/5 is delivered?

**Pull request merged**
